### ISSUE TITLE
Settings 

### ISSUE THREAD

**Issue by Cheesepoofs** [ps-wow/Adibags_ByExpansion#16]
Hey it seems that my settings dosent matter after the last update 1.2.1. I have set it not sort junk from expansions but it still do. And transmog and so on.

**Comment by davidcraig** [comment]
Could you provide a screenshot or a couple of items as examples please? I'll look into it

**Comment by Cheesepoofs** [comment]
Dont know if this is good enough, but went out and got junk from classic 
https://cdn.discordapp.com/attachments/795295859180961802/799254870909648916/unknown.png

**Comment by Cheesepoofs** [comment]
https://www.youtube.com/watch?v=tya14jmCW5E&feature=youtu.be
Made a video playing around with settings. "Just ignore the background sounds"

**Comment by donnie-coleman** [comment]
I have the same issue. Junk is still classified in its expansion category even when the option is unchecked; it prevents me from being able to use the Junk category's "right-click to sell all junk to vendor" feature.

**Comment by davidcraig** [comment]
pushed a commit which should address this, you'll need to be using the "alpha" channel for updates on curseforge/twitch if you aren't already, let me know if it works as expected.

**Comment by donnie-coleman** [comment]
v1.2.1-5-g134d6af-alpha  (I'm using wowup/curse)? it says it was updated 8 days ago but it doesn't work as expected -- I deselected shadowlands junk in the config and reloaded, but the 09. SL - Junk category still shows and it contains items.

edit: I updated to v1.2.1-11g93e4ff4-alpha and works as expected!

**Comment by Cheesepoofs** [comment]
Junk is now working, but others not. Have the same issue with transmog and "other"

**Comment by davidcraig** [comment]
Hi, I have done a large re-code of the logic used in the profile settings, hopefully this should sort most of the issues you were having, I have also added new settings for extra categories, such as anima, conduits, legendaries etc, so you may need to adjust your profile now that these have tick boxes, hope it works for you now (v1.3.0) :)

**Comment by davidcraig** [comment]
Closing issue, if any other problems please either re-open or raise new, thank you :)
