### ISSUE TITLE
lua errors in 10.0

### ISSUE THREAD

**Issue by rainkius** [ps-wow/Adibags_ByExpansion#23]
I am currently getting three errors upon logging in:

**ONE:**

49x Interface/AddOns/AdiBags_ByExpansion/main.lua:318: attempt to index field '?' (a nil value)
[string "@Interface/AddOns/AdiBags_ByExpansion/main.lua"]:318: in function `AddCategoryItems'
[string "@Interface/AddOns/AdiBags_ByExpansion_Shadowlands/main.lua"]:70: in main chunk

Locals:
self = <table> {
 SetDefaultModuleLibraries = <function> defined @Interface/AddOns/Masque/Libs/AceAddon-3.0/AceAddon-3.0.lua:363
 Enable = <function> defined @Interface/AddOns/Masque/Libs/AceAddon-3.0/AceAddon-3.0.lua:290
 AddExpansion = <function> defined @Interface/AddOns/AdiBags_ByExpansion/main.lua:299
 EnableModule = <function> defined @Interface/AddOns/Masque/Libs/AceAddon-3.0/AceAddon-3.0.lua:328
 modules = <table> {
 }
 GetModule = <function> defined @Interface/AddOns/Masque/Libs/AceAddon-3.0/AceAddon-3.0.lua:206
 IterateEmbeds = <function> defined @Interface/AddOns/Masque/Libs/AceAddon-3.0/AceAddon-3.0.lua:438
 GetDefaultCategories = <function> defined @Interface/AddOns/AdiBags_ByExpansion/main.lua:280
 defaultModuleLibraries = <table> {
 }
 LoadExpansion = <function> defined @Interface/AddOns/AdiBags_ByExpansion/main.lua:442
 SetDefaultModulePrototype = <function> defined @Interface/AddOns/Masque/Libs/AceAddon-3.0/AceAddon-3.0.lua:405
 GetOptions = <function> defined @Interface/AddOns/AdiBags_ByExpansion/main.lua:15
 name = "AdiBags_ByExansion"
 IsEnabled = <function> defined @Interface/AddOns/Masque/Libs/AceAddon-3.0/AceAddon-3.0.lua:447
 orderedModules = <table> {
 }
 DisableModule = <function> defined @Interface/AddOns/Masque/Libs/AceAddon-3.0/AceAddon-3.0.lua:346
 DefaultFilter = <function> defined @Interface/AddOns/AdiBags_ByExpansion/main.lua:139
 IsModule = <function> defined @Interface/AddOns/Masque/Libs/AceAddon-3.0/AceAddon-3.0.lua:464
 SetDefaultModuleState = <function> defined @Interface/AddOns/Masque/Libs/AceAddon-3.0/AceAddon-3.0.lua:383
 AddProfessionItems = <function> defined @Interface/AddOns/AdiBags_ByExpansion/main.lua:371
 AddRaidItems = <function> defined @Interface/AddOns/AdiBags_ByExpansion/main.lua:353
 SetEnabledState = <function> defined @Interface/AddOns/Masque/Libs/AceAddon-3.0/AceAddon-3.0.lua:420
 Debug = <function> defined @Interface/AddOns/AdiBags_ByExpansion/main.lua:9
 LoadCategories = <function> defined @Interface/AddOns/AdiBags_ByExpansion/main.lua:393
 GetProfile = <function> defined @Interface/AddOns/AdiBags_ByExpansion/main.lua:116
 baseName = "AdiBags_ByExpansion"
 GetClasses = <function> defined @Interface/AddOns/AdiBags_ByExpansion/main.lua:240
 AddDungeonItems = <function> defined @Interface/AddOns/AdiBags_ByExpansion/main.lua:327
 GetProfessions = <function> defined @Interface/AddOns/AdiBags_ByExpansion/main.lua:257
 IterateModules = <function> defined @Interface/AddOns/Masque/Libs/AceAddon-3.0/AceAddon-3.0.lua:433
 AddCategoryItems = <function> defined @Interface/AddOns/AdiBags_ByExpansion/main.lua:313
 NewModule = <function> defined @Interface/AddOns/Masque/Libs/AceAddon-3.0/AceAddon-3.0.lua:231
 Disable = <function> defined @Interface/AddOns/Masque/Libs/AceAddon-3.0/AceAddon-3.0.lua:310
 enabledState = true
 defaultModuleState = true
 GetName = <function> defined @Interface/AddOns/Masque/Libs/AceAddon-3.0/AceAddon-3.0.lua:275
}
items = <table> {
 1 = 187153
 2 = 187054
 3 = 186685
 4 = 187322
 5 = 187457
 6 = 187324
 7 = 187323
 8 = 187460
 9 = 187458
 10 = 187459
 11 = 187465
 12 = 187327
 13 = 187463
 14 = 187325
 15 = 187326
 16 = 187462
 17 = 187478
 18 = 187336
 19 = 187466
 20 = 187332
 21 = 187328
 22 = 187334
 23 = 187330
 24 = 187329
 25 = 187467
 26 = 187331
 27 = 187311
 28 = 187333
 29 = 187350
 30 = 187335
 31 = 187612
 32 = 187614
 33 = 186984
 34 = 187613
 35 = 187508
 36 = 186718
 37 = 186731
}
category = "Korthia"
module = <table> {
 categories = <table> {
 }
 raids = <table> {
 }
 name = "shadowlands"
 options = <table> {
 }
 prefix = <table> {
 }
 description = "Shadowlands"
 namespace = "Shadowlands"
 dungeons = <table> {
 }
}
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 1 = 187153
 2 = 187054
 3 = 186685
 4 = 187322
 5 = 187457
 6 = 187324
 7 = 187323
 8 = 187460
 9 = 187458
 10 = 187459
 11 = 187465
 12 = 187327
 13 = 187463
 14 = 187325
 15 = 187326
 16 = 187462
 17 = 187478
 18 = 187336
 19 = 187466
 20 = 187332
 21 = 187328
 22 = 187334
 23 = 187330
 24 = 187329
 25 = 187467
 26 = 187331
 27 = 187311
 28 = 187333
 

**TWO:**

46x Interface/AddOns/AdiBags_ByExpansion_Shadowlands/main.lua:1 (null

**THREE:**

46x FrameXML\Bindings.xml:1 Interface/AddOns/AdiBags_ByExpansion_Shadowlands/main.lua:1 (null)

Thank you for any help.

**Comment by davidcraig** [comment]
How do you have the addon installed, eg curseforge or wowup etc, does it show what version you are on as I don't believe I have these errors in game currently

**Comment by rainkius** [comment]
Thank you for your help - I used the CF WoWUp to install it originally. Tried deleting the folders from my addons, and installing it manually (downloaded from Curseforge - AdiBags_ByExpansion-v1.5.0.zip) just now. Upon restarting the game, I get the same errors, unfortunately. :[ 

With ONLY adibags and this plugin enabled, this is the main error (the same, only the stuff under "locals:" is different, but I didn't know if that was useful information):
Message: Interface/AddOns/AdiBags_ByExpansion/main.lua:318: attempt to index field '?' (a nil value)
Time: Sat Nov 12 21:30:22 2022
Count: 1
Stack: Interface/AddOns/AdiBags_ByExpansion/main.lua:318: attempt to index field '?' (a nil value)
[string "@Interface/AddOns/AdiBags_ByExpansion/main.lua"]:318: in function `AddCategoryItems'
[string "@Interface/AddOns/AdiBags_ByExpansion_Shadowlands/main.lua"]:70: in main chunk

Locals: self = <table> {
 SetDefaultModuleLibraries = <function> defined @Interface/AddOns/AdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:363
 Enable = <function> defined @Interface/AddOns/AdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:290
 AddExpansion = <function> defined @Interface/AddOns/AdiBags_ByExpansion/main.lua:299
 EnableModule = <function> defined @Interface/AddOns/AdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:328
 modules = <table> {
 }
 GetModule = <function> defined @Interface/AddOns/AdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:206
 IterateEmbeds = <function> defined @Interface/AddOns/AdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:438
 GetDefaultCategories = <function> defined @Interface/AddOns/AdiBags_ByExpansion/main.lua:280
 defaultModuleLibraries = <table> {
 }
 LoadExpansion = <function> defined @Interface/AddOns/AdiBags_ByExpansion/main.lua:442
 SetDefaultModulePrototype = <function> defined @Interface/AddOns/AdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:405
 GetOptions = <function> defined @Interface/AddOns/AdiBags_ByExpansion/main.lua:15
 name = "AdiBags_ByExansion"
 IsEnabled = <function> defined @Interface/AddOns/AdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:447
 orderedModules = <table> {
 }
 DisableModule = <function> defined @Interface/AddOns/AdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:346
 DefaultFilter = <function> defined @Interface/AddOns/AdiBags_ByExpansion/main.lua:139
 IsModule = <function> defined @Interface/AddOns/AdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:464
 SetDefaultModuleState = <function> defined @Interface/AddOns/AdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:383
 AddProfessionItems = <function> defined @Interface/AddOns/AdiBags_ByExpansion/main.lua:371
 AddRaidItems = <function> defined @Interface/AddOns/AdiBags_ByExpansion/main.lua:353
 SetEnabledState = <function> defined @Interface/AddOns/AdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:420
 Debug = <function> defined @Interface/AddOns/AdiBags_ByExpansion/main.lua:9
 LoadCategories = <function> defined @Interface/AddOns/AdiBags_ByExpansion/main.lua:393
 GetProfile = <function> defined @Interface/AddOns/AdiBags_ByExpansion/main.lua:116
 baseName = "AdiBags_ByExpansion"
 GetClasses = <function> defined @Interface/AddOns/AdiBags_ByExpansion/main.lua:240
 AddDungeonItems = <function> defined @Interface/AddOns/AdiBags_ByExpansion/main.lua:327
 GetProfessions = <function> defined @Interface/AddOns/AdiBags_ByExpansion/main.lua:257
 IterateModules = <function> defined @Interface/AddOns/AdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:433
 AddCategoryItems = <function> defined @Interface/AddOns/AdiBags_ByExpansion/main.lua:313
 NewModule = <function> defined @Interface/AddOns/AdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:231
 Disable = <function> defined @Interface/AddOns/AdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:310
 enabledState = true
 defaultModuleState = true
 GetName = <function> defined @Interface/AddOns/AdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:275
}
items = <table> {
 1 = 187153
 2 = 187054
 3 = 186685
 4 = 187322
 5 = 187457
 6 = 187324
 7 = 187323
 8 = 187460
 9 = 187458
 10 = 187459
 11 = 187465
 12 = 187327
 13 = 187463
 14 = 187325
 15 = 187326
 16 = 187462
 17 = 187478
 18 = 187336
 19 = 187466
 20 = 187332
 21 = 187328
 22 = 187334
 23 = 187330
 24 = 187329
 25 = 187467
 26 = 187331
 27 = 187311
 28 = 187333
 29 = 187350
 30 = 187335
 31 = 187612
 32 = 187614
 33 = 186984
 34 = 187613
 35 = 187508
 36 = 186718
 37 = 186731
}
category = "Korthia"
module = <table> {
 categories = <table> {
 }
 raids = <table> {
 }
 name = "shadowlands"
 options = <ta

**Comment by rainkius** [comment]
OK so I kept poking at it, and compared the shadowlands module's main.lua that's currently here on github to the one I had in my addons folder - There were a few differences (including Korthia category not existing) so I merged them into my version. No errors now, and the categories show up in Adibags!

Thinking this is just curseforge uploading shenanigans... I'm sorry I wasted your time, not sure why it didn't occur to me to check for changes between this version and CF before <facepalm>

**Comment by davidcraig** [comment]
Glad you are sorted, I do remember having issues but I fixed them as I went, pretty sure the latest tag had all that fixed but maybe the updaters are not up to date, i'll add another tag just incase, perhaps it might help

**Comment by davidcraig** [comment]
Turns out I had done a fix just no tag, pushing a new tag now, thanks for reporting the issue :)
