### ISSUE TITLE
Geting error when right-clicking category to sell all items in it

### ISSUE THREAD

**Issue by Rendrir** [ps-wow/Adibags_ByExpansion#26]
When having the vendor window open and then right clicking the category "02. TBC - Equipment (Black Temple)" to sell all the Items to the vendor, the following error appears:

`Message: Interface/AddOns/AdiBags_ByExpansion/main.lua:477: attempt to call global 'UseContainerItem' (a nil value)
Time: Tue Nov 22 13:30:30 2022
Count: 20
Stack: Interface/AddOns/AdiBags_ByExpansion/main.lua:477: attempt to call global 'UseContainerItem' (a nil value)
[string "=(tail call)"]: ?
[string "@Interface/AddOns/AdiBags_ByExpansion/main.lua"]:477: in function ?'
[string "@Interface/AddOns/AdiBags/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:119: in function <...ags/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@Interface/AddOns/AdiBags/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:29: in function <...ags/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:25>
[string "@Interface/AddOns/AdiBags/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:64: in function <...ags/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:59>
[string "=(tail call)"]: ?

Locals: <none>`

This was working before 10.0.2 (2nd PrePatch of Dragonflight)

**Comment by davidcraig** [comment]
Fixed in v1.5.2
