### ISSUE TITLE
War Within LUA error on both 10.2 releases

### ISSUE THREAD

**Issue by Gnathach** [ps-wow/Adibags_ByExpansion#28]
Both 10.2 releases are causing this LUA error every login.  Reverting to an earlier version fixes it.  I checked the folder listed and there is no reputation.lua file in there at all.

6x AdiBags_ByExpansion_WarWithin/categories/reputation.lua:1 Error loading AdiBags_ByExpansion_WarWithin/categories/reputation.lua

**Comment by davidcraig** [comment]
Should be resolved now
