### ISSUE TITLE
Jewelcrafting missing a few things

### ISSUE THREAD

**Issue by MightBeChris** [ps-wow/Adibags_ByExpansion#3]
WotLK JC is missing the epic gems. 36919, 36922, 36931, 36928, 36934, 36925 seem to place themselves in the regular category when others do not.

**Comment by davidcraig** [comment]
Hi,

Apologies for the delay in replying, things have been hectic since christmas, thanks for the items, I have added them in now,they should pop down on the next curse update.

Cheers.
