### ISSUE TITLE
Missing mining items

### ISSUE THREAD

**Issue by vely-digital** [ps-wow/Adibags_ByExpansion#4]
It seems like some mining materials are not in that expansion trade materials(cobalt, saronite, etc). 
Could I pull this and commit something you are missing in new branch and then push it here?

**Comment by davidcraig** [comment]
Absolutely, there are lots of missing items, this is something that takes a long time to build up, and I only started doing this at the end of legion, so there's lots to catch up with.

**Comment by vely-digital** [comment]
Nice! So as I use this addon alot, I'll start updating it when I find something that bothers me.

**Comment by vely-digital** [comment]
I cloned repo and made new branch. I added gathering professions and some tailoring ones to your code. Could I get Permission to upload that branch to git? Then I'll make pull request and you can check code with your PHP scripts.
I'll add more like jewelry and stuff while playing.

**Comment by davidcraig** [comment]
You should have access now, let me know if you have any issues/questions :)

**Comment by davidcraig** [comment]
Closing old issue
